apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-chat-api
  labels:
    app: {{ .Values.deployment.app }}
spec:
  replicas:  {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.app }}
        image:  {{ .Values.deployment.image.repo }}/{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }} # Проверьте порт в документации образа
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379" # Укажите адрес вашего Redis
